### PR TITLE
Add mx-puppet-discord

### PR DESCRIPTION
**Pull request by izissise**
The one last issue is that there is no official docker image, the one specified is 3 months old, and gives no guarantees on what's in it 

I opened an issue on mx-puppet-discord
https://github.com/matrix-discord/mx-puppet-discord/issues/80

#469 
https://github.com/matrix-discord/mx-puppet-discord

### CODE REVIEW

**Comment by Cadair** [comment]
A while ago I hacked together something that builds the docker container locally as part of the playbook: https://github.com/Cadair/matrix-docker-ansible-deploy/blob/dangersalad/roles/matrix-bridge-mx-puppet-discord/tasks/setup_install.yml#L11L34

Not sure if that's a better solution or not.

**Comment by spantaleev** [comment]
We do such "self-building" for various roles. We only currently do it for other architectures (non-amd64) or when explicitly requested.

Learn more here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/self-building.md

If we can, it'd be better if we use a ready-made image, instead of building as part of running the playbook. Would be nice if we can get a more up-to-date image, perhaps by poking upstream :)

**Comment by spantaleev** [comment]
What does logging in as a user vs a bot refer to?

If it works well enough, I guess we could merge this.

**Comment by izissise** [comment]
Sadly, the problem of the source image remains, the current value is the most downloaded mx-puppet-discord image on docker hub.
there is an open issue here https://github.com/matrix-discord/mx-puppet-discord/issues/80

One solution could be enabling image building by default for this bridge

**Comment by jdreichmann** [comment]
@spantaleev Logging in a user is against discords ToS, but allows to bridge DMs and manage friends via matrix.

**Comment by jdreichmann** [comment]
I should add that the version of the docker image the playbook currently uses is outdated enough that the bridge fails to log in.
I succeeded in actually using the bridge by creating a newer image at https://github.com/matrix-discord/mx-puppet-discord/issues/80#issuecomment-650720309, the old version just fails with stacktraces when logging in (probably because discord updated parts of their API)

**Comment by jdreichmann** [comment]
https://github.com/matrix-discord/mx-puppet-discord/issues/80 seems to be resolved, we could point the playbook to `sorunome/mx-puppet-discord:latest` and retest with that

**Comment by izissise** [comment]
Awesome, I'll make the change :)

**Comment by izissise** [comment]
Should be good :)

**Comment by jdreichmann** [comment]
Just tested with the image, everything seems to work

**Comment by izissise** [comment]
I removed the merge commit and rebased from master branch

**Comment by spantaleev** [comment]
Thanks a lot to @izissise for contributing this bridge and for @jdreichmann for testing and pushing for an official image! :+1:

**Pull request merged**
