### PR TITLE
Updated: mautrix-signal to v0.3.0 & signald to 0.18.0

### PR DESCRIPTION
**Pull request by GoliathLabs**
https://github.com/mautrix/signal/releases/tag/v0.3.0

### CODE REVIEW

**Comment by spantaleev** [comment]
Nice! Thanks! :+1:

**Comment by GoliathLabs** [comment]
@borisrunakov normally the 0.18.0 image should correct the permissions and then drop privileges. Yet I had the same error. I did a manually chown and now everything seems to be working

What's your opinion regarding this @spantaleev

**Comment by borisrunakov** [comment]
Chown to `matrix:matrix`?

**Comment by spantaleev** [comment]
We use `--user` when starting it to start it with the `matrix` user (and group), so it probably can't do its thing (start as `root` and drop). We prefer forcing containers into a non-privileged user instead of giving them `root` and hoping/trusting that they'll drop their privileges later.

Does that mean that we need to use the `-non-root` variation of the Signald daemon now? Is this change (root vs non-root) documented somewhere upstream?

**Comment by borisrunakov** [comment]
There is this: https://signald.org/articles/install/docker/#migrating-from-versions-before-0180

**Comment by tulir** [comment]
> the maunium one does not appear up-to-date anymore.

(it's always up to date, but it has never published tags)

**Pull request merged**
