### PR TITLE
Remove default UID/GID

### PR DESCRIPTION
**Pull request by FanchTheSystem**
As on my system 991 is already take, and also as I agree with : https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/65

Thank you for the great work !

### CODE REVIEW

**Comment by FanchTheSystem** [comment]
Also related to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/485

**Comment by spantaleev** [comment]
This is nice! :+1: 

I assume you've tested it out and most services work?

**Comment by FanchTheSystem** [comment]
I tested the whole setup-all/start on my own instance which is already installed (so user matrix already exist)

And I tested the user creation in ansible molecule with a simple playbook:
```yaml
---
- name: Converge
  hosts: all
  remote_user: root
  any_errors_fatal: true
  vars:
    matrix_user_username: matrix
  tasks:
    - name: Ensure Matrix group is created
      group:
        name: "{{ matrix_user_username }}"
        state: present
      register: matrix_group
    - name: Set Matrix Group GID Variable
      set_fact:
         matrix_user_gid: "{{ matrix_group.gid }}"
    - name: Ensure Matrix user is created
      user:
        name: "{{ matrix_user_username }}"
        state: present
        group: "{{ matrix_user_username }}"
      register: matrix_user
    - name: Set Matrix Group UID Variable
      set_fact:
         matrix_user_uid: "{{ matrix_user.uid }}"
    - name: Group Information
      debug:
        var: matrix_user_gid
    - name: User Information
      debug:
        var: matrix_user_uid
```

**Comment by spantaleev** [comment]
Thank you! :+1: 

I've done some minor fixup in 8fea6f5.

It also looks like a dynamic user/group id complicates the "Migrating to a new server" flow, so I've also adjusted that in ccc7aaf.

**Pull request merged**
