### PR TITLE
Update proxied nginx for maubot

### PR DESCRIPTION
**Pull request by Warrows**
I've got a situation where I'm using maubot with gitlab bot. 
My matrix server is setup behind a nginx configured as a proxy.
The bot is giving me error 400 : room not found on webhooks.
The proposed change is working fixes the problem in my situation. However I have not tested it on other configurations nor ran any test.

### CODE REVIEW

**Comment by spantaleev** [comment]
A few questions:

1. Does it really not work without this extra `Host` header?
2. Why not `proxy_pass http://$backend/$request_uri`, instead of messing with `set $backend "matrix-bot-maubot:{{ matrix_bot_maubot_management_interface_port }}";`?
3. Why not apply the same fix to the `{% else %}` clause below as well (for when `matrix_nginx_proxy_enabled: false`)?

**Comment by Warrows** [comment]
1. You're right, it seems to work without the `Host` header.
2. As long as `/$1`is here the fix doesn't work in my situation and I get 404. I need to remove it for it to work. The `$request_uri` (not `/$request_uri`) then can be put at the end of `set $backend` or `proxy_pass`, it's all the same. I just put it where the `/$1` was.
3. I just did not test it but I figure the same could be applied.

**Comment by spantaleev** [comment]
Looks good! Thanks!

**Comment by mjarr** [comment]
@spantaleev
This commit has quote issues. It broke the management interface for me.

**Comment by spantaleev** [comment]
Thanks for reporting this! It should be fixed in https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2149

**Pull request merged**
