### PR TITLE
OCSP Stapling self-signed issue

### PR DESCRIPTION
**Pull request by sakkiii**
Fix https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1073

### CODE REVIEW

**Comment by spantaleev** [comment]
I think we need to make changes to `roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed_obtain_for_domain.yml` to create a `chain.pem` file.

We should also migrate over existing users.

**Comment by aaronraimist** [comment]
Does OCSP Stapling even do anything for a self signed certificate?

**Comment by spantaleev** [comment]
You're right! I guess it doesn't make sense. Disabled here: 9a8a81f

**Comment by sakkiii** [comment]
OCSP Stapling work only with trusted certificates. it will work fine with lets-encrypt.

But again some concern with manual-certs as well

**Comment by m-amir-ir** [comment]
Hello there,

I really agree with @sakkiii about that. 
but I think this line is better : 
```
matrix_nginx_proxy_ocsp_stapling_enabled: "{{ matrix_ssl_retrieval_method == 'lets-encrypt' }}"
```

**Pull request closed without merging**
