### PR TITLE
Mention Let'sEncrypt issues with Element mobile clients

### PR DESCRIPTION
**Pull request by pushytoxin**
Let me know if you'd prefer to have a `matrix_coturn_enable_tls: true/false` variable instead

### CODE REVIEW

**Comment by spantaleev** [comment]
Maybe we should make this the default? If Element doesn't support that, what is there (as of right now) that justifies having it enabled?

**Comment by pushytoxin** [comment]
Using TURNS there is a small benefit of the signaling channel not leaking the remote address during the WebRTC setup.

**Comment by spantaleev** [comment]
Element doesn't support TURNS though, so we don't really get that benefit?

**Comment by pushytoxin** [comment]
Element (mobile) does support TURNS, and even attempts to use it, the issue is specifically with the Let's Encrypt chain. The WebRTC lib uses a different CA root list than that of the operating system.
So if somebody uses external certs, they can enable TURNS. My guess is this is < 1% of those who deploy the playbook.

**Comment by pushytoxin** [comment]
Turning it off by default would leave some people with questions, don't you think? "Why are we reducing the (wrongly perceived) security of the homeservers."

There might be those who currently using the playbook with manually installed certs too. They don't expect changes like this.

I propose we change the default to turn off turns in case the built-in Let'sEncrypt support is disabled.

**Comment by spantaleev** [comment]
> I propose we change the default to turn off turns in case the built-in Let'sEncrypt support is disabled.

Sounds reasonable and likely better than updating some documentation page that no one will read. I've done that in 8b146f083ef3b.

**Comment by pushytoxin** [comment]
I've been away the past week and couldn't work on this, thanks for completing the job! :+1:

**Comment by pushytoxin** [comment]
For the record, these are the issue pages in for the mobile clients:

https://github.com/vector-im/element-android/issues/1533
https://github.com/vector-im/element-ios/issues/2712

**Pull request closed without merging**
