### PR TITLE
add hangouts bridge by copying facebook bridge and find-replacing

### PR DESCRIPTION
**Pull request by microchipster**
This is just a naive copy and find-replace of the facebook -> hangouts right now. I imagine there are some details that need to be worked out, but posting here for discussion.

### CODE REVIEW

**Comment by spantaleev** [comment]
I see that the proxying for `/login` has been fixed to go to `http://matrix-mautrix-hangouts:8080`.

Still, this PR modifies the `matrix-nginx-proxy` role, which it shouldn't, as [mentioned before](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/229#commitcomment-34484773).

**Comment by microchipster** [comment]
FYI this config seems to work now.

**Comment by spantaleev** [comment]
Looks like we just need some documentation page in `docs/` for this bridge.

Would you adapt the Facebook bridge's docs to Hangouts based on your experience?

Not that we can't merge it without it documentation, but it will be more difficult for people to get started.

**Comment by spantaleev** [comment]
Anything else you'd like to do before we merge this?

I see that "admin mode" is still enabled for all homeserver users. We'd better change that before merging. It either needs to be made configurable, or we should at least hardcode safer values (no admin mode at all).

**Pull request merged**
