### PR TITLE
Dendrite 0.7.0

### PR DESCRIPTION
**Pull request by SaltireSoul**
An initial pass at dendrite 0.7.0 support

### CODE REVIEW

**Comment by spantaleev** [comment]
Thank you for bringing us up to date! :+1: 

This fixes #1625.

I wonder if it's a painless upgrade for users on pre-`0.7`.

**Comment by Xemorph** [comment]
Most things look correct so far, but the configuration does not match the `dendrite-config.yml` from the ` v0.7.0` tag. In version `0.7.0` there is still an EDU server & the push server does not exist at that time. See [dendrite-config.yml](https://github.com/matrix-org/dendrite/blob/v0.7.0/dendrite-config.yamll) from tag `v0.7.0`.

@spantaleev 

> I wonder if it's a painless upgrade for users on pre-`0.7`.

I had started to update from version `0.6.5` to version `0.7.0` myself and had several problems with the databases. I was forced to reinstall the server completely. I'm not sure if it was a special case with me, but the commit should be tested first in my opinion.

**Comment by spantaleev** [comment]
While I generally agree that we should be more careful and test things out before merging, it appears that a long time has passed and that we've been stuck on an old Dendrite version (0.5.1) for a long time. There doesn't seem to be anyone in the community that's using Dendrite 0.5.1 and caring to upgrade us to 0.6.0/0.7.0.

It's been a long time (2-3 months since [0.6.0 got released](https://github.com/matrix-org/dendrite/releases/tag/v0.6.0)) and no one has stepped up, so we can probably assume that we can either:

- go ahead and break things for existing users - there are either none of them or none who care much to actually do the migration in a way that works. Perhaps it's Dendrite's fault as well for not providing a cleaner migration path.
- at least be able to continue forward for new users (of who there will be a bigger number) as Dendrite moves forward and becomes more and more feasible. Becoming stuck on 0.5.1 for who knows how long more is not good
- breaking things for existing 0.5.1 users may be some necessary evil (sorry :disappointed:) that needs to be done to have some of them step up and actually fix up the playbook, so that upgrading works.

**Comment by Xemorph** [comment]
Makes sense, then we should create a new base with Dendrite v0.7.0 & migrate reasonably from there. Only one thing worries me a lot, it might happen again soon that the database structure changes (Regarding the Push Server).

But we should revise this for Dendrite again:
```yaml
matrix_dendrite_base_path: "{{ matrix_base_data_path }}/dendrite"
matrix_dendrite_config_dir_path: "{{ matrix_dendrite_base_path }}/config"
matrix_dendrite_storage_path: "{{ matrix_dendrite_base_path }}/storage"
matrix_dendrite_media_store_path: "{{ matrix_dendrite_storage_path }}/media-store"
matrix_dendrite_nats_storage_path: "{{ matrix_dendrite_base_path }}/nats"
matrix_dendrite_ext_path: "{{ matrix_dendrite_base_path }}/ext"
```
because @spantaleev you said the following in the issue #1625 
> A `/matrix-jetstream-parent` (parent, child) kind of thing is not necessary to do here. We do it for the media store, because we're using Goofys for mounting S3 volumes and it's a workaround for some issue with that. Well, this is some `matrix-synapse` legacy. We don't really support Goofys/S3 for Dendrite anyway, so such parent/child hacks are unnecessary. We should probably simplify things.
> 
> For Jetstream, you can just mount a directory directly. We should probably introduce multiple storage paths. Right now we use `matrix_dendrite_storage_path`, but that's just the media store. We should have something like this:
> 
> * `matrix_dendrite_storage_base_path` - as a base path (instead of `matrix_dendrite_storage_path`, which we should deprecate)
> * `matrix_dendrite_storage_jetstream_path` - for Jetstream
> * `matrix_dendrite_storage_media_store_path` - for the media store

---

My suggested solution, off the top of my head:
```yaml
matrix_dendrite_base_path: "{{ matrix_base_data_path }}/dendrite"
matrix_dendrite_config_dir_path: "{{ matrix_dendrite_base_path }}/config"
matrix_dendrite_ext_path: "{{ matrix_dendrite_base_path }}/ext"
matrix_dendrite_storage_base_path: "{{ matrix_dendrite_base_path }}/storage"
matrix_dendrite_storage_jetstream_path: "{{ matrix_dendrite_storage_base_path }}/jetstream"
matrix_dendrite_storage_media_store_path: "{{ matrix_dendrite_storage_base_path }}/media-store"
```
Jetstream & Nats are the same. For the path we should rather go with `nats`, because inside this folder a separate folder `jetstream` is created.

**Pull request merged**
