### PR TITLE
update mautrix-signal

### PR DESCRIPTION
**Pull request by IUCCA**

### CODE REVIEW

**Comment by Jaffex** [comment]
Thanks for the PR, but I've seen that you defaulted the value for `personal_filtering_spaces` to false, whereas for the whatsapp bridge it's turned on by default.

Would it be desirable to keep the same default for all related bridges?

**Comment by IUCCA** [comment]
I only used the default value from the developer's sample configuration. But I can also change the value so that it matches the rest of the playbook

**Comment by wuast94** [comment]
well updated again and got error now. 

```
An unhandled exception occurred while templating '{{ matrix_mautrix_signal_configuration_yaml | from_yaml | combine(matrix_mautrix_signal_configuration_extension, recursive=True) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ lookup('template', 'templates/config.yaml.j2') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected '.'. String: # Homeserver details …
```

**Comment by meyerrj** [comment]
> well updated again and got error now.
> 
> ```
> An unhandled exception occurred while templating '{{ matrix_mautrix_signal_configuration_yaml | from_yaml | combine(matrix_mautrix_signal_configuration_extension, recursive=True) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ lookup('template', 'templates/config.yaml.j2') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected '.'. String: # Homeserver details …
> ```

I've been getting the same error as well. :(

**Pull request merged**
