### PR TITLE
Create QuickStart.md

### PR DESCRIPTION
**Pull request by sbutler-gh**
**Problem:** Navigating the setup pages in the documentation (starting at README.md) is a little confusing.

**Solution:** A one-page guide, walking through a simple/basic/streamlined setup of a Matrix homeserver.

**Next Step:** If we have a successful Quick Start guide, we can also point to it on **README.md** -- for example, updating the README to look like this:

## Purpose

This [Ansible](https://www.ansible.com/) playbook is meant to help you run your own [Matrix](http://matrix.org/) homeserver, along with the [various services](#supported-services) related to that.

That is, it lets you join the Matrix network using your own `@<username>:<your-domain>` identifier, all hosted on your own server (see [prerequisites](docs/prerequisites.md)).

We run all services in [Docker](https://www.docker.com/) containers (see [the container images we use](docs/container-images.md)), which lets us have a predictable and up-to-date setup, across multiple supported distros (see [prerequisites](docs/prerequisites.md)) and [architectures](docs/alternative-architectures.md) (x86/amd64 being recommended).

[Installation](docs/README.md) (upgrades) and some maintenance tasks are automated using [Ansible](https://www.ansible.com/) (see [our Ansible guide](docs/ansible.md)).

## Quick Start

If you want to jump into a streamlined set-up process for a Matrix homeserver, go to [Quick Start](docs/QuickStart.md)

...

### CODE REVIEW

**Comment by skepticalwaves** [comment]
The big risk here is now there's two places to update docs when certain things change.

**Comment by array-in-a-matrix** [comment]
Getting matrix setup using the existing documentation is pretty quick imo. I feel like adding a quick start guide is redundant.

**Comment by robbyoconnor** [comment]
There is nothing wrong with the existing docs, to be honest. This shouldn't be made easier if people can't follow those.

**Comment by robbyoconnor** [comment]
> The big risk here is now there are two places to update docs when certain things change.

This is a valid point **_AGAINST_** this change. Why do we need this? 

I sit in the chat and see how few people seem to read the docs. 

The existing documentation works fine. People are just too lazy and not willing to sit down and read. This is the dumbest thing like it really shouldn't be a thing. It's redundant.

**Comment by spantaleev** [comment]
Agreed! Closing this.

**Pull request closed without merging**
