### PR TITLE
Mautrix whatsapp

### PR DESCRIPTION
**Pull request by izissise**
Add mautrix-whatsapp

Tested for two days, and it works well :)

### CODE REVIEW

**Comment by spantaleev** [comment]
Wow, that's great to see!

Let's wait for the mautrix-whatsapp PR to get merged and let's merge this!

By the way, recently I've been thinking about restructuring the default variables file (`defaults/main.yml`).
As we add more features, it's starting to get longer and some related variables are too far apart or prefixed differently.

For example, the currently-named `matrix_docker_image_mautrix_whatsapp` would probably be better named as `matrix_whatsapp_docker_image` (or something like that), bringing it all under the common (`matrix_whatsapp_` prefix).. As well as bringing all these variables closer together in the file.

I know we have to redo this for many other things as well, so that will be some future work (no need to water-down this PR's patch-set with such stuff).

**Comment by izissise** [comment]
@rubo77 I don't know, that's the name of the project :D

I agree on the variable renaming 👍

**Comment by izissise** [comment]
Good for merge !

**Comment by spantaleev** [comment]
Merged and added a documentation link! Thanks @izissise! :+1:

**Pull request merged**
