### PR TITLE
only enable openssl if necessary, closes #1510 

### LINKED ISSUE #1510: Ensure OpenSSL installed and use matrix_host_command_openssl
I need openssl for #1505 and searched the repo for it and found these:

1. [matrix-nginx-proxy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b1b4ba501fdfaa434dac8a981cec9ac0311ca4ef/roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed.yml) has a task to install it if using self-signed certs
2. some jitsi script wants to use it
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/30339cd313717bf18471f39ee27db76ec3ba2ddf/inventory/scripts/jitsi-generate-passwords.sh#L6
3. there is a global variable with the path to it
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/61391647e9681968f65096223507c6645ad03acb/roles/matrix-base/defaults/main.yml#L82
4. which is used by matrix-bridge-appservice-irc
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/1ab507349c752042d26def3e95884f6df8886b74/roles/matrix-bridge-appservice-irc/tasks/setup_install.yml#L100

What needs to be done:
1. extract the installation from (1) so that all roles depending on it can install it
2. jitsi (2) should use the variable (3)
3. use both of these features for #1505

### PR DESCRIPTION
**Pull request by altsalt**
Changes not applied to [hookshot PR](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1505).

### CODE REVIEW

**Comment by spantaleev** [comment]
Nice! Thanks! :+1:

**Comment by HarHarLinks** [comment]
shouldn't this also set `matrix_host_command_openssl`?

**Comment by altsalt** [comment]
Where? Sorry if something was missed, I was mostly following the suggested PR.

**Comment by HarHarLinks** [comment]
currently it gets set by
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5e2f4564bbfc4572832068f564a858f14a1406a4/roles/matrix-base/defaults/main.yml#L97

currently it gets used by
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/b33ea48803b0414dced910ebcec520c1eaaa4c99/roles/matrix-bridge-appservice-irc/tasks/setup_install.yml#L102

If it exists, shouldn't everyone use it via the variable? Though I'm not firm enough with ansible to tell what advantages using `"/usr/bin/env openssl"` might have over a plain call. I suppose the idea is you can switch out the openssl binary used by overriding the variable?

**Pull request merged**
