### PR TITLE
Allow changing Riot bug report URL

### PR DESCRIPTION
**Pull request by TheLastProject**
Just want to make sure users of our hosted instance won't bug the Matrix team ;)

### CODE REVIEW

**Comment by TheLastProject** [comment]
Actually, wait, this is not actually the bug report URL. I think this is where debug logs may be sent? Hmm...

**Comment by aaronraimist** [comment]
That’s the same thing. Anyway unless you are customizing like the actual features of Riot for yourself, you are running the same Riot as anyone else so the bug reports are just as valid.

**Comment by TheLastProject** [comment]
Well sure they are valid, but I worry corporate end-users will see the link and report "help I can't login" there, you know? Non-Riot issues. Better to be able to filter those first.

**Comment by aaronraimist** [comment]
Sure. (for that issue specifically though, you can only report bugs once you are logged in)

**Pull request closed without merging**
