### PR TITLE
"Federate rooms" switch for mautrix bridges

### PR DESCRIPTION
**Pull request by MrAnno**
This PR makes it configurable whether portal rooms created by mautrix bridges will be federatable or not.

Note: Rooms cannot transition from unfederated to federated after creation.

### CODE REVIEW

**Comment by spantaleev** [comment]
Adding `|to_json` for good measure is probably a good idea.

So the default is "let them be federateable"? Given that for most bridges you're not an administrator in the room and that gaining invite-privileges and inviting others is of limited purpose, I wonder why the upstream default is not to prevent federation.

**Comment by MrAnno** [comment]
Thank you for the review.

I'm pretty new to Matrix, so I think I won't have a good answer to this question.
I believe the "default on" policy may have something to do with the limitation that non-federatable rooms can not be converted to federatable later.

It seems there is no server-side default federation switch at all (at least in Synapse); but for example, Element has its own frontend option:
https://github.com/vector-im/element-web/blob/f975d85806263c9f7b1750e53de8da0274dfb02c/config.sample.json#L30

A silly question: why do we use `|to_json` when formatting mautrix templates (YAML files)?

**Comment by spantaleev** [comment]
> A silly question: why do we use `|to_json` when formatting mautrix templates (YAML files)?

YAML is a superset of JSON, so we put data into YAML configuration by using `|to_json`. We can use `|to_yaml `too to achieve the same, I suppose -- although YAML usually has 10 different ways to represent the same thing and it's more unpredictable what `|to_yaml` would do.

To get back as to "why", it's because values (especially `string` values) can contain special characters that need to be escaped when embedding them into YAML (JSON) text.

**Comment by MrAnno** [comment]
@spantaleev Thanks for the explanation.
I've updated the pull request.

**Pull request merged**
