### PR TITLE
fix wrong json parameter in webhook documentation

### PR DESCRIPTION
**Pull request by MarcProe**
fixes HTTP 400 Error: "{\"errcode\":\"M_MISSING_PARAM\",\"error\":\"Missing key 'avatar_url'\"}"

### CODE REVIEW

**Comment by spantaleev** [comment]
Are you sure?

The README for the project (https://github.com/turt2live/matrix-appservice-webhooks) says `avatarUrl`.

Searching for that also yields some results: https://github.com/turt2live/matrix-appservice-webhooks/search?q=avatarUrl

It also makes sense. Who would name this `avatarUrl`, while also using `displayName` - that's inconsistent.

**Comment by aaronraimist** [comment]
Related: https://github.com/turt2live/matrix-appservice-webhooks/issues/72

**Comment by spantaleev** [comment]
Thanks for finding that!

It sounds like that bridge is quite broken and even with `avatar_url`, it may not work well.

**Comment by MarcProe** [comment]
I use the bridge with IFTTT to forward SMS. It works quite decently (if you use the "correct" parameter).
image

**Comment by spantaleev** [comment]
Alright! Let's merge this as it is, given that it works. Thank you! :+1:

**Pull request merged**
