### PR TITLE
Add variables to fine tune jitsi

### PR DESCRIPTION
**Pull request by pcorace**
I was doing several tests with jitsi. I was able to improve CPU and bandwidth consumption by adjusting parameters as per the recommendations at https://jitsi-club.gitlab.io/jitsi-self-hosting/en/01-deployment-howto/03-tuning/
I found it useful to add some variables to better manipulate these values.

### CODE REVIEW

**Comment by pcorace** [comment]
For example, in my vars.yml I configured the following values:
# Jitsi Fine Tune
matrix_jitsi_web_config_disable_AudioLevels: true
matrix_jitsi_web_config_enable_LayerSuspension: true
matrix_jitsi_web_config_channelLastN: 4
matrix_jitsi_web_config_enable_Video_Constraints: true

# This settings work if matrix_jitsi_web_config_enable_Video_Constraints: true
matrix_jitsi_web_config_aspectRatio: 16/9
matrix_jitsi_web_config_height_ideal: 480
matrix_jitsi_web_config_height_max: 480
matrix_jitsi_web_config_height_min: 240

**Comment by spantaleev** [comment]
Hi!

Thank you for discovering this and for contributing! :+1: 

I'd like to merge it, but think some of these options can be named in a more consistent way with the rest of the playbook.

We usually try to stick to names as they appear in the component we're configuring. That is:
- a `disableAudioLevels` for `jitsi-web` should be named: `matrix_jitsi_web_config_disableAudioLevels` (not `matrix_jitsi_web_config_disable_AudioLevels` - having a needless underscore there).
- configuring `contraints.video.aspectRatio` should ideally happen via `matrix_jitsi_web_config_constraints_video_aspectRatio` (not `matrix_jitsi_web_config_aspectRatio`).
- settings for enabling/disabling things (such as your `matrix_jitsi_web_config_enable_Video_Constraints`) should ideally be named (`something_something_enabled`) to be in line with what we do everywhere else (e.g. `matrix_riot_web_enabled`, `matrix_jitsi_enabled`, etc.). This one should ideally be renamed to `matrix_jitsi_web_config_constraints_enabled`. Seems like there's currently no default value for this setting. It would also be nice if we add `matrix_jitsi_web_config_constraints_enabled: false` to `defaults/main.yml`, above the default constraint values.

If doing this renaming is too much work for you, let me know and I can take care of it before merging!

**Comment by pcorace** [comment]
Thank you for your comments!
I'm going to rename the variables and add some comments about their use.

**Comment by pcorace** [comment]
Are these variable names correct?

# Jitsi Fine Tune default values.
# Useful to manage bandwidth and CPU consumption in server and client side
matrix_jitsi_web_config_disableAudioLevels: false
matrix_jitsi_web_config_enableLayerSuspension: false
matrix_jitsi_web_config_channelLastN: -1
# If 'matrix_jitsi_web_config_constraints_enabled: false'
# the video constraints will be disabled and will take the default values of jitsi
matrix_jitsi_web_config_constraints_enabled: false
# This settings work if matrix_jitsi_web_config_constraints_enabled: true
# See their definitions in config.js.j2 (templates / web)
matrix_jitsi_web_config_constraints_video_aspectRatio: 16/9
matrix_jitsi_web_config_constraints_video_height_ideal: 720
matrix_jitsi_web_config_constraints_video_height_max: 720
matrix_jitsi_web_config_constraints_video_height_min: 240

(sorry for my english ... rewrite the comments as you like ...)

**Comment by spantaleev** [comment]
Yes, it looks good!

Would you be updating your PR or should I do it?

**Comment by spantaleev** [comment]
Thanks a lot for your diligent work! :+1:

**Pull request merged**
