### PR TITLE
Updated: jitsi to stable-6865

### PR DESCRIPTION
**Pull request by GoliathLabs**
It looks like we don't need to change anything on the configurations on our side. But I would be happy if someone could double check this

### CODE REVIEW

**Comment by spantaleev** [comment]
It would be nice if someone who's using Jitsi could give this a test.

**Comment by GoliathLabs** [comment]
@spantaleev can you assign a "help wanted" label or similar to this PR? That way others can better participate in the review of this PR.

**Comment by etkecc** [comment]
It works!
Tested on etke.cc server.

**Comment by spantaleev** [comment]
Thanks for confirming! Merged! :+1:

**Pull request merged**
