### PR TITLE
Updated: registration to v0.9.1

### LINKED ISSUE #1541: [TASK] Update matrix-registration to v0.9.1
Hello,
I opened this issue because the version of matrix-registration currently in use is outdated. It might help to keep an eye on the update and discuss below if something needs to be done before creating a PR for the new update.

### Changelog
- the registration page is now available in english and german
- the changes of 0.9.0 and 0.9.1 might require some changes here as well as the api's endpoints are now available under the /api/ subdirectory
https://github.com/ZerataX/matrix-registration/releases

### PR DESCRIPTION
**Pull request by GoliathLabs**
Updates the registration image tag to v0.9.1. I've also updated the config file to match the changes in the upstream one (https://github.com/ZerataX/matrix-registration/blob/master/config.sample.yaml). I'd be happy if one could have a look at it.
Closes #1541

### CODE REVIEW

**Comment by spantaleev** [comment]
Are you updating components blindly?

As far as I know, 0.9.1 doesn't work due to these 2 issues:

- https://github.com/ZerataX/matrix-registration/issues/72
- https://github.com/ZerataX/matrix-registration/issues/73

**Comment by GoliathLabs** [comment]
Sorry, I haven't seen those issues. I think I'll make this a draft instead then until things are sorted out at the upstream project

**Comment by spantaleev** [comment]
The [wip-matrix-registration-upgrade branch](https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/wip-matrix-registration-upgrade) (well, f5b92d183291acdfd) already does the same (+ more) to bring us up to date with v0.9.1+.

**Comment by GoliathLabs** [comment]
Alright, I'll close it then. But thank you for reviewing this. I'll have a better look into the changes next time.

**Pull request closed without merging**
