### PR TITLE
Update matrix-synapse-admin version

### PR DESCRIPTION
**Pull request by skepticalwaves**
Not yet tested.

### CODE REVIEW

**Comment by skepticalwaves** [comment]
Blocked by https://github.com/Awesome-Technologies/synapse-admin/issues/186

**Comment by danrmiller** [comment]
Is this still blocked and untested?

**Comment by aaronraimist** [comment]
0.8.3 still doesn't exist on Docker Hub

**Comment by skepticalwaves** [comment]
In the meantime, I've been using the "latest" tag successfully

**Comment by spantaleev** [comment]
Looks like the next tagged release of synapse-admin should be pushed to Docker Hub, thanks to https://github.com/Awesome-Technologies/synapse-admin/pull/187 ?

So we just need to see 0.8.4 tagged and we'd be good to go?

**Comment by skepticalwaves** [comment]
> So we just need to see 0.8.4 tagged and we'd be good to go?

Yes and update the version tag of course. I'll close this now until that happens.

**Comment by aaronraimist** [comment]
@skepticalwaves 0.8.4 is out now and I can confirm self building is working properly.

**Pull request closed without merging**
