### PR TITLE
Add mautrix-wsproxy role (to enable mautrix-imessage/Beeper's Brooklyn)

### PR DESCRIPTION
**Pull request by hanthor**
This is likely messed up, I still need to test, I stole work from the mautrix-amp PR and from the Whatsapp role. I still need to spin up a dev build to test it

### CODE REVIEW

**Comment by holeyness** [comment]
Is the merge request feature complete? I'm happy to help test and report back any issues

**Comment by hanthor** [comment]
I merged changes into my fork. Not sure if it works

**Comment by holeyness** [comment]
Ok, I will test out these changes and report back.

**Comment by holeyness** [comment]
Just tested this PR, with a couple of changes the server side builds, deploys and starts successfully. Now I'm testing whether the actual bridge will work.

**Pull request closed without merging**
