### PR TITLE
Add Go Skype Bridge

### PR DESCRIPTION
**Pull request by CyberShadow**
Based on mautrix-whatsapp, as that's what the bridge software is based on.

This one logs me in successfully, unlike mx-puppet-skype, which seems to be dead right now.

I'm not 100% sure that 100% of the added lines are correct - haven't tested things like database migration, just the basic functionality.

### CODE REVIEW

**Comment by spantaleev** [comment]
Looks great! Thank you for adding `go-skype-bridge` support! :+1:

**Comment by RoiArthurB** [comment]
Quick question : Any idea if it works on arm64? 🤔🤔🤔

**Comment by CyberShadow** [comment]
> Quick question : Any idea if it works on arm64?

I don't know, but I think it should. It's written in Go, so I don't expect much trouble. We also need to build a Docker image either way because the project doesn't provide one, so we know that works at least.

**Comment by RoiArthurB** [comment]
I tried the compilation on my Raspberry Pi 4 and it works (not sure yet for the runtime) !

 <details>
  <summary>Full log here</summary>

```
$ docker build . -t localhost/roiarthurb/go-skype-bridge:latest
Sending build context to Docker daemon  851.5kB
Step 1/13 : FROM golang:1-alpine3.14 AS builder
1-alpine3.14: Pulling from library/golang
455c02918c45: Pull complete 
125ff9128fc6: Pull complete 
d1fa2c4bb9ec: Pull complete 
7731466d147a: Pull complete 
e2e442908f7f: Pull complete 
Digest: sha256:70ba8ec1a0e26a828c802c76ecfc65d1efe15f3cc04d579747fd6b0b23e1cea5
Status: Downloaded newer image for golang:1-alpine3.14
 ---> 63e5da64a214
Step 2/13 : RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev
 ---> Running in 7f0efacecf48
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/30) Installing libgcc (10.3.1_git20210424-r2)
(2/30) Installing libstdc++ (10.3.1_git20210424-r2)
(3/30) Installing binutils (2.35.2-r2)
(4/30) Installing libmagic (5.40-r1)
(5/30) Installing file (5.40-r1)
(6/30) Installing libgomp (10.3.1_git20210424-r2)
(7/30) Installing libatomic (10.3.1_git20210424-r2)
(8/30) Installing libgphobos (10.3.1_git20210424-r2)
(9/30) Installing gmp (6.2.1-r1)
(10/30) Installing isl22 (0.22-r0)
(11/30) Installing mpfr4 (4.1.0-r0)
(12/30) Installing mpc1 (1.2.1-r0)
(13/30) Installing gcc (10.3.1_git20210424-r2)
(14/30) Installing musl-dev (1.2.2-r3)
(15/30) Installing libc-dev (0.7.2-r3)
(16/30) Installing g++ (10.3.1_git20210424-r2)
(17/30) Installing make (4.3-r0)
(18/30) Installing fortify-headers (1.1-r1)
(19/30) Installing patch (2.7.6-r7)
(20/30) Installing build-base (0.5-r2)
(21/30) Installing brotli-libs (1.0.9-r5)
(22/30) Installing nghttp2-libs (1.43.0-r0)
(23/30) Installing libcurl (7.79.1-r1)
(24/30) Installing expat (2.4.7-r0)
(25/30) Installing pcre2 (10.36-r0)
(26/30) Installing git (2.32.2-r0)
(27/30) Installing olm (3.2.3-r0)
(28/30) Installing pkgconf (1.7.4-r0)
(29/30) Installing olm-dev (3.2.3-r0)
(30/30) Installing su-exec (0.2-r1)
Executing busybox-1.33.1-r7.trigger
OK: 209 MiB in 45 packages
Removing intermediate container 7f0efacecf48
 ---> 8781c0d34bcc
Step 3/13 : COPY . /build
 ---> 472fe9c2e5cc
Step 4/13 : WORKDIR /build
 ---> Running in f935c7296bf7
Removing intermediate container f935c7296bf7
 ---> a42357e1ff33
Step 5/13 : RUN go build -o /usr/bin/matrix-skype
 ---> Running in d6ea2f2fa24e
go: downloading github.com/gabriel-vasile/mimetype v1.1.2
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/kelaresg/go-skypeapi v0.1.2-0.20210813144457-5bc29092a74e
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading maunium.net/go/mauflag v1.0.0
go: downloading maunium.net/go/maulogger/v2 v2.3.1
go: downloading github.com/pidongqianqian/mautrix-go v0.10.4-0.20211208080648-321c4f849adb
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: downloading github.com/gorilla/mux v1.8.0
go: downloading golang.org/x/net v0.0.0-20211020060615-d418f374d309
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
go: downloading github.com/btcsuite/btcutil v1.0.2
go: downloading github.com/tidwall/gjson v1.10.2
go: downloading github.com/tidwall/sjson v1.2.3
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/PuerkitoBio/goquery v1.5.1
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/gogf/gf v1.13.0
go: downloading github.com/andybalholm/cascadia v1.1.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading github.com/spf13/afero v1.1.2
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/jwalterweatherman v1.0.0
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
go: downloading golang.org/x/text v0.3.6
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
Removing intermediate container d6ea2f2fa24e
 ---> 1ecf7203a576
Step 6/13 : FROM alpine:3.14
3.14: Pulling from library/alpine
455c02918c45: Already exists 
Digest: sha256:06b5d462c92fc39303e6363c65e074559f8d6b1363250027ed5053557e3398c5
Status: Downloaded newer image for alpine:3.14
 ---> ac73e934f311
Step 7/13 : ENV UID=1337     GID=1337
 ---> Running in 4f363f3b711d
Removing intermediate container 4f363f3b711d
 ---> 7ec1aeb08e58
Step 8/13 : RUN apk add --no-cache ffmpeg su-exec ca-certificates olm bash jq yq curl
 ---> Running in 6aaee094f2a7
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/74) Installing ncurses-terminfo-base (6.2_p20210612-r0)
(2/74) Installing ncurses-libs (6.2_p20210612-r0)
(3/74) Installing readline (8.1.0-r0)
(4/74) Installing bash (5.1.16-r0)
Executing bash-5.1.16-r0.post-install
(5/74) Installing ca-certificates (20211220-r0)
(6/74) Installing brotli-libs (1.0.9-r5)
(7/74) Installing nghttp2-libs (1.43.0-r0)
(8/74) Installing libcurl (7.79.1-r1)
(9/74) Installing curl (7.79.1-r1)
(10/74) Installing sdl2 (2.0.14-r1)
(11/74) Installing libxau (1.0.9-r0)
(12/74) Installing libmd (1.0.3-r0)
(13/74) Installing libbsd (0.11.3-r0)
(14/74) Installing libxdmcp (1.1.3-r0)
(15/74) Installing libxcb (1.14-r2)
(16/74) Installing libx11 (1.7.2-r0)
(17/74) Installing aom-libs (1.0.0-r3)
(18/74) Installing alsa-lib (1.2.5-r2)
(19/74) Installing expat (2.4.7-r0)
(20/74) Installing libbz2 (1.0.8-r1)
(21/74) Installing libpng (1.6.37-r1)
(22/74) Installing freetype (2.10.4-r3)
(23/74) Installing libuuid (2.37.4-r0)
(24/74) Installing fontconfig (2.13.1-r4)
(25/74) Installing fribidi (1.0.10-r0)
(26/74) Installing libffi (3.3-r2)
(27/74) Installing libintl (0.21-r0)
(28/74) Installing libblkid (2.37.4-r0)
(29/74) Installing libmount (2.37.4-r0)
(30/74) Installing pcre (8.44-r0)
(31/74) Installing glib (2.68.3-r0)
(32/74) Installing graphite2 (1.3.14-r0)
(33/74) Installing harfbuzz (2.8.1-r0)
(34/74) Installing libass (0.15.1-r0)
(35/74) Installing libdav1d (0.9.0-r0)
(36/74) Installing gmp (6.2.1-r1)
(37/74) Installing nettle (3.7.3-r0)
(38/74) Installing p11-kit (0.23.22-r0)
(39/74) Installing libtasn1 (4.17.0-r0)
(40/74) Installing libunistring (0.9.10-r1)
(41/74) Installing gnutls (3.7.1-r0)
(42/74) Installing lame (3.100-r0)
(43/74) Installing opus (1.3.1-r1)
(44/74) Installing libgomp (10.3.1_git20210424-r2)
(45/74) Installing soxr (0.1.3-r2)
(46/74) Installing libgcc (10.3.1_git20210424-r2)
(47/74) Installing libstdc++ (10.3.1_git20210424-r2)
(48/74) Installing libsrt (1.4.2-r0)
(49/74) Installing libssh (0.9.6-r0)
(50/74) Installing libogg (1.3.5-r0)
(51/74) Installing libtheora (1.1.1-r16)
(52/74) Installing libjpeg-turbo (2.1.0-r0)
(53/74) Installing v4l-utils-libs (1.20.0-r0)
(54/74) Installing libxext (1.3.4-r0)
(55/74) Installing libxfixes (6.0.0-r0)
(56/74) Installing libdrm (2.4.106-r0)
(57/74) Installing wayland-libs-client (1.19.0-r0)
(58/74) Installing libva (2.11.0-r0)
(59/74) Installing libvdpau (1.4-r0)
(60/74) Installing vidstab (1.1.0-r1)
(61/74) Installing libvorbis (1.3.7-r0)
(62/74) Installing libvpx (1.10.0-r0)
(63/74) Installing vulkan-loader (1.2.170-r1)
(64/74) Installing libwebp (1.2.0-r2)
(65/74) Installing x264-libs (20210211-r0)
(66/74) Installing x265-libs (3.4-r0)
(67/74) Installing xvidcore (1.3.7-r1)
(68/74) Installing ffmpeg-libs (4.4.1-r0)
(69/74) Installing ffmpeg (4.4.1-r0)
(70/74) Installing oniguruma (6.9.7.1-r0)
(71/74) Installing jq (1.6-r1)
(72/74) Installing olm (3.2.3-r0)
(73/74) Installing su-exec (0.2-r1)
(74/74) Installing yq (4.6.3-r3)
Executing busybox-1.33.1-r7.trigger
Executing ca-certificates-20211220-r0.trigger
OK: 71 MiB in 88 packages
Removing intermediate container 6aaee094f2a7
 ---> 0f89f0f49349
Step 9/13 : COPY --from=builder /usr/bin/matrix-skype /usr/bin/matrix-skype
 ---> 81a8767cfedb
Step 10/13 : COPY --from=builder /build/example-config.yaml /opt/matrix-skype/example-config.yaml
 ---> bea7b057dca4
Step 11/13 : COPY --from=builder /build/docker-run.sh /docker-run.sh
 ---> a517e334affa
Step 12/13 : VOLUME /data
 ---> Running in 5e267fd66e2d
Removing intermediate container 5e267fd66e2d
 ---> 941f9e1b1334
Step 13/13 : CMD ["/docker-run.sh"]
 ---> Running in 7c6df5539abd
Removing intermediate container 7c6df5539abd
 ---> 20599d0c1824
Successfully built 20599d0c1824
Successfully tagged localhost/roiarthurb/go-skype-bridge:latest
```

</details> 

I also made a PR to have pre-made images for AMD64 and ARM64 architectures that you can follow here : https://github.com/kelaresg/go-skype-bridge/pull/17 :smile:

**Pull request merged**
