### PR TITLE
Fixed self-build functionality for mautrix-signal

### PR DESCRIPTION
**Pull request by Toorero**
I now autodetect compatible platforms of the mautrix-signal docker images via the manifest and added overlooked self-build functionality for the signal daemon.

Follow-up to  #1175

### CODE REVIEW

**Comment by Toorero** [comment]
Also, I think it would be cool to append a notice to docs/configuring-playbook-bridge-mautrix-signal.md about a possible occurring self-build issue of signald which just spits out a cryptic Gradle error and is just a result of to low memory 🤷🏻

**Comment by spantaleev** [comment]
Looks like you're currently not setting `matrix_mautrix_signal_container_self_build` via `group_vars/matrix_servers`? You're only seeing the signal daemon self-build variable.

**Comment by Toorero** [comment]
Yes because the signal container itself has a manifest which describes for which architecture it is compatible. Therefore, the docker pull will fail automatically and I start the self build process.

**Comment by Toorero** [comment]
OK I'm not sure how the review thing works and how I can cite code but just look up to the comments I left at the concerning lines.

**Comment by spantaleev** [comment]
So you're trying to pull and then fall back to building if it fails?

Sounds like this is more fragile than just pulling for platforms where we know pulling works.

Right now, `docker_image`-pulling that fails for another reason (temporary network error, etc.) will probably also trigger self-building.

**Comment by Toorero** [comment]
That's actually right, but I think it's a better approach because if somehow he drops support for the arm64 build or adds another platform to the manifest, it just works out of the box. Also, the pulling of the source code will fail if there is a network error.

Perhaps I can just ignore fails if the platform is not equal to amd64 or arm64 but that would diminish the whole point.

If you don't like the approach, you can just revert to the old approach I implemented in #1175 . I totally understand your reasoning, but don't like the hard coded platform approach.

**Comment by spantaleev** [comment]
Yes, I think an approach where we hardcode the the known-working platforms to be more stable and predictable. It's also more in line with what we do in all other roles.

**Comment by Toorero** [comment]
Ok, I reverted to the manual approach you proposed. I hope everything is now to your liking 😅

**Comment by Toorero** [comment]
uff you're right I overlooked some stuff

**Comment by Toorero** [comment]
thx 🙏🏻

**Comment by spantaleev** [comment]
I've removed some references that were left from before.

Looks good! Thank you for fixing self-building! :+1:

**Pull request merged**
