### PR TITLE
Caddy2 Caddyfile example and Comment in examples/host_vars.yml

### PR DESCRIPTION
**Pull request by 0hlov3**

### CODE REVIEW

**Comment by spantaleev** [comment]
Thank you for your contribution!

Can you get rid of the `.DS_Store` file?

**Comment by 0hlov3** [comment]
So i updated the Caddyfile again, but it seems that everything is working now for me. And i deleted the .DS_Store now.
I put it also in the .gitignore, hopefully its okay for you.

**Comment by 0hlov3** [comment]
I also updated the variable matrix_dimension_integrations_ui_url in roles/matrix-dimension/defaults/main.yml, so it points to /element not /riot

"integrations_ui_url": "https://dimension.t2bot.io/element",

https://dimension.t2bot.io/

**Comment by spantaleev** [comment]
That's nice! Thank you! :+1:

**Pull request merged**
