### PR TITLE
Improve security for grafana

### PR DESCRIPTION
**Pull request by sakkiii**
- removed duplicate X-Content-Type-Options
- removed duplicate X-Frame-Options header
- Referrer-Policy [Might consider adding variable]
- Secure flag with cookies
- matrix_grafana_content_security_policy variable for [Content Security Policy](https://grafana.com/docs/grafana/latest/administration/configuration/#content_security_policy)

### CODE REVIEW

**Comment by spantaleev** [comment]
Thanks! :+1:

**Comment by aaronraimist** [comment]
@sakkiii does grafana actually work for you with the CSP enabled? It doesn't for me. Shows some error saying try refreshing the page and in the browser console is several CSP violations.

**Comment by sakkiii** [comment]
@aaronraimist yeah it does work for me. i just checked with Firefox, Brave(based on the Chromium) & Safari for all working fine.
Can you share browser logs?

**Comment by aaronraimist** [comment]
@sakkiii This is what I see in Safari:



Grafana does seem to work in Firefox but there are a bunch of things being blocked by the CSP

**Comment by sakkiii** [comment]
@aaronraimist unable to regenerate similar issue but added backward compatible with older browsers.
Could you review this, may solve your problem #1036

**Comment by aaronraimist** [comment]
@sakkiii interestingly as of today I cannot reproduce it with or without that patch. 🤷‍♂️

**Pull request merged**
