### PR TITLE
Add mjolnir

### LINKED ISSUE #353: Add Mjolnir (moderation bot)
https://github.com/matrix-org/mjolnir is a moderation bot intended for use within individual communities. For those who spin up a homeserver for their community, Mjolnir would be a good fit.

This request is for the bot to be added, not the Synapse module (because that's complicated). Docker images are available on Docker Hub: https://hub.docker.com/r/matrixdotorg/mjolnir

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes #353

This is just the bot portion of mjolnir, not the synapse module.

Todo:
- [x] Write docs
- [x] Figure out why the first start doesn't work
  - It seems to start before Synapse so it crashes but after it automatically restarts then it works fine. I thought this is what the `..systemd_required_services_list` variable was for but I have Synapse in there and it doesn't seem to make a difference.

### CODE REVIEW

**Comment by spantaleev** [comment]
It'd be nice to have! Thanks for working on this!

----------

> Figure out why the first start doesn't work

Maybe the bot is too quick to start and too quick to try and hit Synapse (or die during this initial attempt?).

`..systemd_required_services_list` just makes one systemd service require another. systemd will make sure to start services in accordance, but this does not guarantee that services are actually fully running and usable.

A service can signal to systemd that it's started and usable using this [`sd_notify`](https://www.man7.org/linux/man-pages/man3/sd_notify.3.html) thing. However, Synapse needs to support it, and doing that from within a Docker container probably comes with quite some complication (I haven't looked into it lately).

--------

Speaking of Mjolnir, and looking at its README, I'm starting to wonder if we should work on a `matrix-pantalaimon` role as well.

**Comment by aaronraimist** [comment]
I tried adding `ExecStartPre={{ matrix_host_command_sleep }} 10` (and 20 and 30) but that doesn't seem to help. The bot starts first (after waiting for nothing for 10 seconds). I'm not sure if misconfiguration or systemd bug or what. This is the service file that is generated:

```
[Unit]
Description=Matrix Mjolnir bot
Requires=docker.service
After=docker.service
Requires=matrix-synapse.service
After=matrix-synapse.service
Requires=matrix-postgres.service
After=matrix-postgres.service
Wants=docker.service
Wants=matrix-synapse.service
Wants=matrix-postgres.service
DefaultDependencies=no

[Service]
Type=simple
Environment="HOME=/root"
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker kill matrix-bot-mjolnir 2>/dev/null'
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker rm matrix-bot-mjolnir 2>/dev/null'

# Intentional delay, so that the homeserver (we likely depend on) can manage to start.
ExecStartPre=/usr/bin/env sleep 10

ExecStart=/usr/bin/env docker run --rm --name matrix-bot-mjolnir \
			--log-driver=none \
			--user=991:991 \
			--cap-drop=ALL \
			--read-only \
			--network=matrix \
			--mount type=bind,src=/matrix/mjolnir/config,dst=/data/config,ro \
			--mount type=bind,src=/matrix/mjolnir/data,dst=/data \
			docker.io/matrixdotorg/mjolnir:v0.1.17

ExecStop=-/usr/bin/env sh -c '/usr/bin/env docker kill matrix-bot-mjolnir 2>/dev/null'
ExecStop=-/usr/bin/env sh -c '/usr/bin/env docker rm matrix-bot-mjolnir 2>/dev/null'
Restart=always
RestartSec=30
SyslogIdentifier=matrix-bot-mjolnir

[Install]
WantedBy=multi-user.target
``` 

> Speaking of Mjolnir, and looking at its README, I'm starting to wonder if we should work on a matrix-pantalaimon role as well.

Wouldn't hurt for someone to work on that but I am not likely to work on that in the near future. Mjolnir works fine for what I need it to do without E2E.

**Comment by aaronraimist** [comment]
Added a few more services to depend on and that seems to work OK. Just finishing up the docs and then this will be ready to merge./

**Comment by aaronraimist** [comment]
Okay I think this is ready to go

**Comment by spantaleev** [comment]
Thanks a lot! Happy to see the playbook supporting more and more bots! :+1:

**Pull request merged**
