### PR TITLE
Update Synapse (1.39.0 -> 1.40.0)

### PR DESCRIPTION
**Pull request by wol-win**

### CODE REVIEW

**Comment by skepticalwaves** [comment]
Release notes https://github.com/matrix-org/synapse/releases/tag/v1.40.0

**Comment by wol-win** [comment]
> 
> 
> Release notes https://github.com/matrix-org/synapse/releases/tag/v1.40.0

These release notes have been linked probably only for documentary reasons, right? Or did I miss something?

**Comment by spantaleev** [comment]
Thank you! :+1:

**Comment by skepticalwaves** [comment]
> > Release notes https://github.com/matrix-org/synapse/releases/tag/v1.40.0
> 
> These release notes have been linked probably only for documentary reasons, right? Or did I miss something?

Yes, just for docs.

**Pull request merged**
