### PR TITLE
Clarify documentation on port forwarding of Jitsi/TRP behind NAT

### PR DESCRIPTION
**Pull request by cnvandijk**
Depending on your firewall/NAT setup, incoming RTP packets may have as destination address the external IP of your firewall and not your Matrix/Jitsi server. This is important if your port forwarding rules are filtered by destination IP.

This caught me for a while, and may be the issue behind #519, so I figured it would be good to add it to the docs.

### CODE REVIEW

**Comment by spantaleev** [comment]
`../roles/matrix-jitsi/defaults/main.yml#L147` will probably get outdated quickly.

Maybe it's better to link to the file and mention `matrix_jitsi_jvb_stun_servers`.

I'm not sure how one should correct the problem though? Can you elaborate some more on what you did to make it work for you?

**Comment by spantaleev** [comment]
Thanks! :+1:

**Comment by cnvandijk** [comment]
Our firewall filters not only based on port number but destination address. All other packets intended for this playbook come in with the IP defined in the DNS, but the RTP packets come in with the firewall's external IP. Until we come up with a better solution, we just added an extra rule for these packets.

For the record it is also possible to skip STUN completely and just hardcode the IP with something like ([docs](https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#mapping-harvesters)):
```
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<container-ip>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<dns-ip>
```
but it requires putting the container on a fixed IP in the docker network.

**Comment by andreas-dc** [comment]
Adding "DOCKER_HOST_ADDRESS=xxx" to ../matrix-docker-ansible-deploy/roles/matrix-jitsi/templates/jvb/env.j2 is the only thing, you need to let the jvb start-up script define

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<container-ip>
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<docker host ip>

... by itself (making it obsolete to use aws, tcp harvesting or stun).

**Pull request merged**
