### PR TITLE
Feature: add synapse worker support

### PR DESCRIPTION
**Pull request by maxklenk**
The [PR](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456) of @eMPee584 is stale for quite a while. I would like to take over to implement this feature.

#### Docs:
* Synapse: https://github.com/matrix-org/synapse/blob/develop/docs/workers.md

#### Usage

To enable worker support, simply set the `matrix_synapse_workers_enabled` flag to true. There are defaults on how many workers of which kind are started in `matrix_synapse_workers_enabled_list`. In addition your database should allow more connections to support all workers.
```yaml
#
# Synapse config
#
matrix_synapse_workers_enabled: true

#
# Postgres config
#
matrix_postgres_process_extra_arguments: [
  "-c 'max_connections=200'"
]
```

#### Tasks:
* [x] use new worker names
* [x] use new worker routes
* [x] deploy redis when workers are enabled
* [x] add redis configuration for workers
* [ ] check cleanup of worker processes/config when they are changed/renamed

### CODE REVIEW

**Comment by eMPee584** [comment]
Thanks for chiming in Max! Some of the checkboxes (redis) can be ticked, please have a look at the original PR #456 .. had been working on this last week but got too deep into trying to automatically parse the [synapse workers dox](https://github.com/matrix-org/synapse/blame/master/docs/workers.md) .. converting my awk script* into perl and such non-sense. Also have a bunch of other stuff going on, and a tmux session with >60 windows (so maybe 150 terminal commands/apps running) really gets a bit confusing when combined with a sleep deficit 🤪
Anyway, I just force-pushed my rebased branch and some fragments of the necessary updates and will try to have it up running ASAP.. there's not much more missing.

[*] `parse-workers-docs.awk`
```
#!/usr/bin/awk
# ^ the most hackish approach to get a machine-readable list
# of current matrix REST API endpoint regular expressions from
# invoke in shell with:
# URL=https://github.com/matrix-org/synapse/raw/master/docs/workers.md
# curl -L ${URL} | awk -f parse-workers-docs.awk -

# Enable further processing only at the end of the preamble.
# Read each synapse worker section as record and its lines as fields.
/Available worker applications/ {
    enable_parsing = 1
    # set record separator to markdown sub-header
    RS = "### "
    # set field separator to newline
    FS = "\n"
}

# Each worker record should start with a synapse.app.X headline
enable_parsing && /synapse.app/ {
    # get rid of the backticks, then store the worker type
    gsub("`", "", $1)
    worker_type = $1

    # loop through the lines (1 - number of fields in record)
    for (i = 1; i <= NF; i++) {
        # and parse those looking like URLs
        if ($i ~ /^ +[\^/].*\//) {
            gsub(/^ +/, "", $i)
            api_endpoint_regex = $i
            print worker_type ": '" api_endpoint_regex "'"
        }
    }
}

# vim: tabstop=4 shiftwidth=4 expandtab autoindent
```

**Comment by maxklenk** [comment]
Hey @eMPee584 nice to see that you picked it up again. I would like to support, eg. your nginx configuration still contains the old workers/routes.

**Comment by eMPee584** [comment]
You mean, the parts I committed yesterday..
i usually try to have proper, atomic & tested commits.. so sometimes, things lie around in my work tree for a while before they are being committed even though practically ready..
Ah well, redundant implementation may be effort duplication in some cases, but also provides the benefit of validation. So keep going if you like, even though I might already have done a part of a task and it just remains to be committed and pushed.. :wink:

**Comment by PC-Admin** [comment]
Big thanks to eMPee584 and @maxklenk for trying to get this working, it's a very important addition to this deploy script.

**Comment by ptman** [comment]
how can we help you guys push this over the finish line?

**Comment by maxklenk** [comment]
I am running this branch in a beta test with about 15000 users right now to see if everything runs smooth under load. 
I tried to include the feedback from PR https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/456 but it would be great to get a review of my changes to finish this.

**Comment by eMPee584** [comment]
I'll have another go at it today.. 😅

**Comment by PC-Admin** [comment]
an idiot-proof guide on how to get the latest workers pull:
```
$ git clone https://github.com/spantaleev/matrix-docker-ansible-deploy.git
$ cd ./matrix-docker-ansible-deploy/
$ git fetch origin pull/642/head:maxtesting
$ git checkout maxtesting
```

Then add this to your vars.yml:
```
matrix_synapse_workers_enabled: true
```

then just re-run the playbook with setup-all,start

seems to run okay so far, good work max

**Comment by PC-Admin** [comment]
Had a bit more of a play, here is how it breaks the postgres service file:

```
ExecStart=/usr/bin/env docker run --rm --name matrix-postgres \
                        --log-driver=none \
                        --user=1001:1001 \
                        --cap-drop=ALL \
                        --read-only \
                        --tmpfs=/tmp:rw,noexec,nosuid,size=100m \
                        --tmpfs=/run/postgresql:rw,noexec,nosuid,size=100m \
                        --network=matrix \
                        --env-file=/matrix/postgres/env-postgres-server \
                        -v /matrix/postgres/data:/var/lib/postgresql/data:rw \
                        -v /etc/passwd:/etc/passwd:ro \
                        postgres:12.4-alpine \
                        postgres \
```
The bottom line and preceding slash is what breaks it, this might just be because of my crude merging though. xD

**Comment by bobbythefett** [comment]
I tested this PR with my homeserver. It did not work with the defaults.
- My server went from a load average of 2 to 20+ (maybe too much workers for a small/medium server by default?)
- Nginx configuration did not work with my own nginx. The lines added for the workers were not working, even after the load reduced.

**Comment by PC-Admin** [comment]
Have been running 3 workers for a few days now with no real issues:
```
# Synapse/Redit Workers
matrix_synapse_workers_enabled: true
matrix_synapse_workers_enabled_list:
  - { worker: generic_worker, port: 18101 }
  - { worker: generic_worker, port: 18102 }
  - { worker: federation_sender, port: 18401 }
```

Just ran with these settings, then fixed the broken postgres service file. CPU time seems to be climbing on the synapse processes but the service is very responsive now. :) Thanks again.

**Comment by PC-Admin** [comment]
One error i think might be related is 2/3rds of the time uploads fail to complete with error message: 'The file 'XXX' failed to upload. in Element.

I believe this is the synapse workers failing to handle the request, and it only completes when the main synapse thread handles the request.

**Comment by PC-Admin** [comment]
I tried to revert to 1 worker like so yet i still see the 2 generic workers in htop:
```
# Synapse/Redit Workers
matrix_synapse_workers_enabled: false
matrix_synapse_workers_enabled_list:
  - { worker: generic_worker, port: 18101 }
  - { worker: generic_worker, port: 18102 }
  - { worker: federation_sender, port: 18401 }

~THEN~

# Synapse/Redit Workers
matrix_synapse_workers_enabled: true
matrix_synapse_workers_enabled_list:
  - { worker: federation_sender, port: 18401 }
```

Interestingly enough the port mapping is correct, so these 2 generic workers shouldn't be able to access the web:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                                                                                                  NAMES
76d2e06cf4a5        matrixdotorg/synapse:v1.19.1    "python -m synapse.a…"   3 minutes ago       Up 3 minutes        8008-8009/tcp, 8448/tcp, 0.0.0.0:18401->18401/tcp, 0.0.0.0:9000->9100/tcp                                                              matrix-synapse
```

We also see that the services are still available:
```
# systemctl list-units --type=service --state=running
matrix-synapse-worker@federation_sender:18401.service loaded active running Synapse Matrix Worker                       
matrix-synapse-worker@generic_worker:18101.service    loaded active running Synapse Matrix Worker                       
matrix-synapse-worker@generic_worker:18102.service    loaded active running Synapse Matrix Worker                       
matrix-synapse-worker@user_dir:18601.service          loaded active running Synapse Matrix Worker
```

**Comment by localguru** [comment]
@PC-Admin 
> One error i think might be related is 2/3rds of the time uploads fail to complete with error message: "The file 'XXX' failed to upload." in Element.

Have you tried to add a media_repository worker to split the upload from generic workers?

**Comment by eMPee584** [comment]
I rebased my branch on this PR and added proper (hopefully) cleansing of left-over workers, please try if the problem persists with the recent commits on #456 ..

**Comment by maxklenk** [comment]
I'll close this PR in favour to finish the work in #456

**Pull request closed without merging**
