### PR TITLE
according to discussion in channel not needed anymore

### PR DESCRIPTION
**Pull request by dreamflasher**

### CODE REVIEW

**Comment by spantaleev** [comment]
So the bridge handles authentication later on, after you message it?

If so, we should also remove other references to these variables too. There are some in:

- `roles/matrix-bridge-mx-puppet-slack/defaults/main.yml`
- `roles/matrix-bridge-mx-puppet-slack/templates/config.yaml.j2`

**Comment by dreamflasher** [comment]
Apparently, because the authentication is done per slack workspace/team with the bot itself. Shall I remove the other references as well?

**Comment by spantaleev** [comment]
Yes, please. Let's remove them and get this merged

**Comment by spantaleev** [comment]
Thanks! :+1:

**Pull request merged**
