### PR TITLE
Update prerequisites.md

### PR DESCRIPTION
**Pull request by real-joshua**
Document that sudo is required.

### CODE REVIEW

**Comment by real-joshua** [comment]
To me it's not clear that sudo is required, only that access as root is required.

**Comment by real-joshua** [comment]
It does not say `and` but `or`, it is ambiguous.

**Comment by spantaleev** [comment]
Maybe the docs page should say:

> Root access or sudo installed, so the playbook can ultimately elevate to root

.. instead of adding a separate line asking for sudo in all cases (even when you have direct root access)

**Comment by real-joshua** [comment]
Well, without `sudo` the Playbool fails at a point where it uses it, even if you run as root. So it'd be good to add that somewhere specifically.

**Comment by spantaleev** [comment]
You're right - I've tried with direct `root` access and it seems like Ansible requires `sudo` even then during the "Gathering facts" task:

```
TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
fatal: [HOST]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    ansible.legacy.setup:
      failed: true
      module_stderr: |-
        /bin/sh: 1: sudo: not found
      module_stdout: ''
      msg: |-
        MODULE FAILURE
        See stdout/stderr for the exact error
      rc: 127
  msg: |-
    The following modules failed to execute: ansible.legacy.setup
```

I've relocated the `sudo` requirement line to be next to the other server-related requirements in the `docs/prerequisites.md` file and have reworded the text a bit.

Thank you for bringing this up!

**Pull request merged**
