### PR TITLE
change port 8090 to matrix_ma1sd_default_port

### PR DESCRIPTION
**Pull request by borisrunakov**
Changed hard coded port 8090 to `matrix_ma1sd_default_port` wherever possible.

### CODE REVIEW

**Comment by spantaleev** [comment]
Thanks! :+1: 

We do hard code ports like that a lot and it's nice to move away from it.

**Comment by borisrunakov** [comment]
I have overseen one part though, will fix it now. Are there any tests I can run before the PR ? i.e. doing the self test will only test functionality based on settings on `vars.yaml`. Do you have something to test every possible use case ?

**Comment by spantaleev** [comment]
The self-test is meant for users to check if some important ports on their server are open (which indicates important services are running). It's not meant as a unit/integration test for us while developing. Unfortunately, we don't have such a thing (yet).

**Comment by borisrunakov** [comment]
Good to know! Will try to think of some unit / integration tests.

**Pull request merged**
