### PR TITLE
Added Traefik configuration example to own webserver docs

### PR DESCRIPTION
**Pull request by lpulley**
@spantaleev helped me get this working with Traefik as a reverse proxy. I've added my working configuration to the docs with ample comments and explanation.

### CODE REVIEW

**Comment by spantaleev** [comment]
Thank you! :+1: 

-------

I've noticed that you're wiring federation directly to Synapse (`matrix-synapse:8048`).

You could probably make it go to nginx as well (`matrix-nginx-proxy:8448`) - that in-container `8448` port serves plain-HTTP traffic when `matrix_nginx_proxy_https_enabled` is `false`.

If so, everything would go to matrix-nginx-proxy and Synapse can remain as-is.

**Comment by spantaleev** [comment]
Ah, I see [from your comment](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/296#issuecomment-562819174) there may be some reason why you're making `matrix-nginx-proxy:8448` go unused and going for reverse-proxying directly to `matrix-synapse:8048`. Perhaps Traefik makes it more difficult to set up with multiple ports going to the same service.

**Comment by lpulley** [comment]
Yes, the way the Traefik Docker provider works, I don't see a way to map two entrypoints to two different ports. Figured it would be fine to just patch through to Synapse since that's all Nginx does anyway.

**Comment by spantaleev** [comment]
Got it! Sounds good then!

**Pull request merged**
