### PR TITLE
Use pre-build arm64 version of Hydrogen image

### PR DESCRIPTION
**Pull request by mattcen**
This PR is pending vector-im/hydrogen-web#948, but assuming that gets merged, this one will be good to go; I've already tested that the resulting arm64 image works on my arm64 system.

### CODE REVIEW

**Comment by saket424** [comment]
@mattcen 
I made the one line edit per your pull request and set matrix_architecture: arm64 and matrix_client_hydrogen_enabled: true in vars.xml . When I run 

ansible-playbook -i inventory/hosts setup.yml --tags=setup-all

It seems to be downloading the amd64 hydrogen-web docker image instead of the arm64 docker image. What am I doing wrong or am i missing a step?

```
-matrix_client_hydrogen_container_image_self_build: "{{ matrix_architecture not in ['amd64'] }}"
+matrix_client_hydrogen_container_image_self_build: "{{ matrix_architecture not in ['arm64', 'amd64'] }}"
```

**Comment by saket424** [comment]
I have temporarily added this line to my vars.xml and it seemed to do the trick

matrix_client_hydrogen_docker_image: 'ghcr.io/mattcen/hydrogen-web@sha256:26efb832e8b3739f2640b3215e03ab6918c51d3a3870f5cc43a7e6c2da14f38f'

**Comment by mattcen** [comment]
As per the description of this PR (which is still in Draft state for this very reason), it is pending the merging of another PR with the Hydrogen to actually build multi-arch images; currently the only build amd64 images.

**Comment by mattcen** [comment]
> I have temporarily added this line to my vars.xml and it seemed to do the trick
> 
> matrix_client_hydrogen_docker_image: 'ghcr.io/mattcen/hydrogen-web@sha256:26efb832e8b3739f2640b3215e03ab6918c51d3a3870f5cc43a7e6c2da14f38f'
> 

Furthermore, my Hydrogen fork is not kept updated with upstream, so I advise against using this container image long-term.

**Comment by saket424** [comment]
Of course, now that I know it is fixable, I'll build my own arm64 docker container using master HEAD. Thanks

**Comment by spantaleev** [comment]
Done in [d76a5c1](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/d76a5c14d024a99b1e6e65e86da6f3b9f4590e53)

**Pull request closed without merging**
