### PR TITLE
Revert Grafana Version to v11.1.1-0

### PR DESCRIPTION
**Pull request by wuast94**
Latest available tag is 11.1.1 https://hub.docker.com/r/grafana/grafana/tags

### CODE REVIEW

**Comment by wuast94** [comment]
would close #3449

**Comment by wuast94** [comment]
intresting, the grafana-oss image is already on 11.1.3 https://hub.docker.com/r/grafana/grafana-oss/tags

**Comment by spantaleev** [comment]
Our Ansible role was recently switched to start using grafana-oss

**Comment by wuast94** [comment]
but it tries to dowload the grafana/grafana image, not the oss one

**Comment by wuast94** [comment]
its fefaulting to the oss one:
https://gitlab.com/etke.cc/roles/grafana/-/blob/main/defaults/main.yml?ref_type=heads#L104

but when i run the playbook: 
```
TASK [galaxy/grafana : Ensure Grafana image is pulled] *************************************************************************************************************************************************************************************************************
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (10 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (9 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (8 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (7 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (6 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (5 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (4 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (3 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (2 retries left).
FAILED - RETRYING: [matrix.3ddruckbremen.de]: Ensure Grafana image is pulled (1 retries left).
fatal: [matrix.3ddruckbremen.de]: FAILED! => changed=false 
  attempts: 10
  msg: 'Error pulling image docker.io/grafana/grafana:11.1.3 - 404 Client Error for http+docker://localhost/v1.45/images/create?tag=11.1.3&fromImage=docker.io%2Fgrafana%2Fgrafana: Not Found ("manifest for grafana/grafana:11.1.3 not found: manifest unknown: manifest unknown")'
  ```

**Comment by spantaleev** [comment]
Try `just roles` again. The playbook had not been updated to `v11.1.3-1` of the Grafana Ansible role, but it is now.

**Comment by wuast94** [comment]
that worked, thanks for the quick reaction 😊

**Pull request closed without merging**
