### PR TITLE
matrix-appservice-slack: improved documentation

### PR DESCRIPTION
**Pull request by daudo**
better described how to get channel id, added a section how to unlink a channel and a troubleshooting section

### CODE REVIEW

**Comment by spantaleev** [comment]
Wasn't the original meaning the same? Open the channel in the browser and check the URL?

I guess the original didn't explain very much, but what we have after this patch is essentially the same thing explained in 2 different ways and these 2 ways being offered as alternatives?

Or am I misunderstanding something?

Maybe the explanation should be like this:

> * Determine the "channel ID" that Slack uses to identify the channel. You will see it when you open a given Slack channel in a browser. The URL reads something like this: `https://app.slack.com/client/XXX/<the channel id>/details/`.

**Comment by daudo** [comment]
Even after some clicking around, I wasn't able to figure out where the original URL came from, but I thought I'd let the original URL there, just in case I am missing something.

So yes, your explanation makes perfect sense. I'll update accordingly.

As I walk through the steps laid out in the documentation, I've noted some additional things (most notably troubleshooting stuff) that I'll add to my PR, if you wish.

**Comment by spantaleev** [comment]
If these other things are unrelated to the Slack bridge, we can probably do them in another PR :)

Thanks for keeping track of things and improving the docs!

**Comment by daudo** [comment]
I've updated the PR to only have one way to retrieve the channel id plus added a section about unlinking and troubleshooting

**Comment by spantaleev** [comment]
Much more detailed! Thank you! :+1:

**Pull request merged**
