### PR TITLE
Fix template indentation

### PR DESCRIPTION
**Pull request by danbob**
This yaml template wouldn't compile until I changed all the flow control lines to two leading spaces.

### CODE REVIEW

**Comment by spantaleev** [comment]
I cannot reproduce this problem with Ansible 2.7.10 and Jinja 2.10.1.
The YAML template compiles even as it is.

What is your setup like? Let's figure out what necessitates such kind of fixes.

**Comment by danbob** [comment]
I have the same versions. Do you have `matrix_mxisd_threepid_medium_email_custom_templates_enabled: true`? I didn't have trouble until I set that.

I dug into it a bit more and this is sufficient to fix the problem:

```yaml
# roles/matrix-mxisd/defaults/main.yml

matrix_mxisd_configuration_yaml: |
  #jinja2: lstrip_blocks: True
  matrix: ...
```

**Comment by spantaleev** [comment]
Yes.

To test it out, I've used the following configuration:

```yaml
matrix_mxisd_threepid_medium_email_custom_templates_enabled: true
matrix_mxisd_threepid_medium_email_custom_invite_template: test
```

.. and it created the configuration and template file successfully.

I wonder what `#jinja2: lstrip_blocks: True` has to do with fix this particular issue. Hmm..

**Comment by danbob** [comment]
It was harder than I expected to come up with a minimum fail condition, but here it is: the problem only occurs if either of the *other* templates are set:
```yaml
matrix_mxisd_threepid_medium_email_custom_templates_enabled: true

matrix_mxisd_threepid_medium_email_custom_session_validation_template: test
# and/or
matrix_mxisd_threepid_medium_email_custom_matrixid_template: test
```
I think jinja by default only strips out the block tags themselves and not the leading whitespace unless you set that option. So the resulting yaml ends up with these blank lines with just whitespace in them, and the yaml parser is choking on some of them.

**Comment by spantaleev** [comment]
Wow, great find! :+1: 

Looks like the `#jinja2: lstrip_blocks: True` fix is better (preserves the nice indentation we have and is not fragile to future additions).

We have a few more variables that this fix can be applied to:

- `matrix_dimension_configuration_yaml`
- `matrix_appservice_irc_configuration_yaml`

These don't contain any `{% if %}` logic, so they don't suffer from the problem at the moment, but it's nice if we future-proof them.

Would you update your PR to apply `#jinja2: lstrip_blocks: True` to all of these and to not change the indentation of `matrix_mxisd_configuration_yaml`?

**Comment by danbob** [comment]
Done!

**Comment by spantaleev** [comment]
Thanks for finding and fixing this weird issue with #108! :+1:

**Pull request merged**
