### PR TITLE
Add conduit homeserver

### LINKED ISSUE #1290: Any thoughts on adding Conduit.rs?
Wanted to see if there was any possibility of this ansible expanding to include Conduit.rs as an alternative to Synapse in the ansible deploy. Maybe for lower resource deployments.

### PR DESCRIPTION
**Pull request by kubo6472**
Fixes #1290 
Copied over from dendrite and replaced the docker image and var names. Already adding this as a PR so no double work is happening. Any help appreciated.

### CODE REVIEW

**Comment by spantaleev** [comment]
Looks like there are various `dendrite` references in this still. More replacements are needed.

Thanks for getting us started on supporting Conduit! :+1:

**Comment by cvwright** [comment]
Doh!  Somehow I missed this one when I started on #2002

**Comment by spantaleev** [comment]
Seems like I had reviewed this, but had completely forgotten about it too.

I suppose yours will be more up to date, and you'd be more responsive to get it merged.

**Comment by kubo6472** [comment]
Closing in favor of #2002

**Pull request closed without merging**
