### PR TITLE
Add wechat bridge

### PR DESCRIPTION
**Pull request by tobiasdiez**
Adds a bridge for WeChat. Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/701 and https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3092.

The bridge itself is working, but the agent and the agent config needs a bit more work. I currently cannot test it as my server is running on ARM and the agent doesn't currently support this, see https://github.com/duo/matrix-wechat-agent/pull/6.

So if someone wants to give this a try and report back if it's working on x64, this would be great. Also any suggestions for improvement are already very welcome.

### CODE REVIEW

**Comment by Korben57** [comment]
I only have the one host and im using it for my main matrix setup rn, I'll let you know if I get access to another to test on

**Comment by spantaleev** [comment]
I've polished up this PR and merged it into the playbook.

Beside some bugfixes and polishing, the biggest change I've done is renaming the role (`matrix-bridge-go-wechat` to `matrix-bridge-wechat`) and its variables (`matrix_go_wechat` -> `matrix_wechat`).

Thank you for contributing WeChat support, @tobiasdiez!

Once I receive a WeChat invitation, I may test it in full myself. Until then, it'd be nice if others could jump in and do some testing.

**Comment by tobiasdiez** [comment]
@spantaleev Thanks for polishing and merging it!

**Comment by Korben57** [comment]
Thanks guys appreciate it! 🙏

**Comment by Korben57** [comment]
@tobiasdiez I raised issue #3352 this evening, not sure if its something for you or for @spantaleev but I'm eager to test as I have a WeChat account waiting to be bridged!

**Pull request closed without merging**
