### PR TITLE
Added docker-compose example for launching Traefik.

### PR DESCRIPTION
**Pull request by enekonieto**
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/687

### CODE REVIEW

**Comment by spantaleev** [comment]
One is supposed to use this in combination with `matrix_docker_network: traefik`, right?

**Comment by enekonieto** [comment]
Yes. The snippet is in the [Sample configuration for running behind Traefik 2.0](https://github.com/enekonieto/matrix-docker-ansible-deploy/blob/feature/traefik_docker_compose/docs/configuring-playbook-own-webserver.md#sample-configuration-for-running-behind-traefik-20) section, and the provided configuration in that section expects `matrix_docker_network: 'traefik'`.

**Comment by spantaleev** [comment]
Oh, sorry! I overlooked it.

Thanks a lot! :+1:

**Comment by enekonieto** [comment]
@spantaleev, I want to merge another commit, should I open a new pull request? Thanks!

**Comment by spantaleev** [comment]
Yes, please! This one has already been merged and closed.

**Pull request merged**
