### PR TITLE
Goofys Custom Endpoint Support

### PR DESCRIPTION
**Pull request by console-cowboy**
Goofys can work with more than just Amazon S3. _Hopefully_ this is all it takes to enable configuring a custom endpoint for custom endpoints like Minio.

### CODE REVIEW

**Comment by spantaleev** [comment]
Thank you! :+1:

**Comment by spantaleev** [comment]
@wabuMike, thanks for catching this! :+1: 

It was indeed missing an `if` there. I've fixed it up.

**Comment by wabuMike** [comment]
Another thing that didn't work for me was `if matrix_s3_media_store_custom_endpoint_enabled is false`. Had to put `if matrix_s3_media_store_custom_endpoint_enabled == false` to make it work.

**Comment by spantaleev** [comment]
I've changed that to `{% if not matrix_s3_media_store_custom_endpoint_enabled %}` in the same commit, so it should be okay now.

**Pull request merged**
