### PR TITLE
Add worker metrics to prometheus exporter

### PR DESCRIPTION
**Pull request by Cadair**
I tried a few ways of doing this in various levels of insanity. This was the only way I could come up with that actually worked, but I appreciate it's using a synapse variable in the prometheus role.

### CODE REVIEW

**Comment by spantaleev** [comment]
It'd be nice to make this not use `matrix_synapse_` variables.

We can probably pass this `matrix_synapse_workers_enabled_list` variable as-is via `group_vars/matrix_servers`.

**Comment by Cadair** [comment]
So just put in `group_vars/matrix_servers` something like

```
matrix_prometheus_synapse_workers_enabled_list: "{{ matrix_synapse_workers_enabled_list }}"
```
?

That's easy enough.

**Comment by spantaleev** [comment]
It's not pretty (there may be a cleaner way to do it), but it works.

**Comment by Cadair** [comment]
done :)

**Comment by spantaleev** [comment]
Thank you! :+1:

**Pull request merged**
