### PR TITLE
Resolve Synology DSM 7.2 Docker Command Issue 

### PR DESCRIPTION
**Pull request by cksit**
I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.

After that, I specified the DSM Docker location in my vars file as follows:
`devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`

It would be appreciated if this change can be approved.

### CODE REVIEW

**Comment by spantaleev** [comment]
Thank you! Good to hear it's possible to use this playbook against a Synology host!

**Comment by Twolitrepinto** [comment]
#

> I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.
> 
> After that, I specified the DSM Docker location in my vars file as follows: `devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`
> 
> It would be appreciated if this change can be approved.

Hi, I'm currently trying to make this work on DSM 7.2.
I've successfully installed it in a VM, but would rather install it directly into DSM because I already run other docker containers, and I feel this way would make better use of it's limited resources.
The docker issue you mention isn't an issue for me because I already use docker for other containers, so I don't need the playbook to install that, i just add the command in vars.yml to skip it.

The issue I do have is that the playbook fails as it can't find the NTP service, as in DSM it is named ntpd.
I saw in another "issue", someone modified it in the source code, but I wouldn't know how to do that myself.

How did you work around this please?
Thanks in advance.

**Comment by Twolitrepinto** [comment]
Nevermind, I managed to get past the ntp problem, now have a problem with it failing on adding Matrix group.

**Comment by cksit** [comment]
> > I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.
> > After that, I specified the DSM Docker location in my vars file as follows: `devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`
> > It would be appreciated if this change can be approved.
> 
> Hi, I'm currently trying to make this work on DSM 7.2. I've successfully installed it in a VM, but would rather install it directly into DSM because I already run other docker containers, and I feel this way would make better use of it's limited resources. The docker issue you mention isn't an issue for me because I already use docker for other containers, so I don't need the playbook to install that, i just add the command in vars.yml to skip it.
> 
> The issue I do have is that the playbook fails as it can't find the NTP service, as in DSM it is named ntpd. I saw in another "issue", someone modified it in the source code, but I wouldn't know how to do that myself.
> 
> How did you work around this please? Thanks in advance.

The issue I mentioned has been solved after merging this branch to the main branch. 
So you won't have the same issue again.

For NTP service in DSM7, below is the configuration I used in vars.yml. 
```YAML
# this is the NTP service for DSM7. 
devture_timesync_ntpd_service: "chronyd"
```

For me, I haven't tried with VM approach due to the very limited resource of Synology NAS. And I don't want to maintain my own branch to make this playbook working in DSM7 by modifying the source code.

By using the latest version of this project and a correctly configured `vars.yml` file, you should be able to execute this playbook directly in DSM7 with a little bit `tweak`  by using DSM Terminal.

**Comment by Twolitrepinto** [comment]
Thank you so much for the quick reply.

I don't suppose you recall the names of the required users and groups?

I will do the other bits now.
Thanks again!

**Comment by cksit** [comment]
> Thank you so much for the quick reply.
> 
> I don't suppose you recall the names of the required users and groups?
> 
> I will do the other bits now. Thanks again!

Just create a normal user and user group with the permission you want in DSM.
And enable the home folder for that user.
Use command `id` to check the user id and group id and put the value in the `vars.yml` file

**Comment by Twolitrepinto** [comment]
> > Thank you so much for the quick reply.
> > I don't suppose you recall the names of the required users and groups?
> > I will do the other bits now. Thanks again!
> 
> Just create a normal user and user group with the permission you want in DSM. And enable the home folder for that user. Use command `id` to check the user id and group id and put the value in the `vars.yml` file

Thanks for your time.

I have created the user and group and got the id's, but I can't figure out how to put them in the vars.yml?
Sorry to be a pain. 
Thank you for all your help.

**Comment by spantaleev** [comment]
You can change the username/group, as well as the uid/gid with these variables:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/66a2584b0e8626c3ed4f78798bab1dbd0679e016/roles/custom/matrix-base/defaults/main.yml#L138-L145

**Comment by Twolitrepinto** [comment]
> You can change the username/group, as well as the uid/gid with these variables:
> 
> https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/66a2584b0e8626c3ed4f78798bab1dbd0679e016/roles/custom/matrix-base/defaults/main.yml#L138-L145

Thank you, that worked.

I feel I am getting close, however unfortunately I now have another issue:

`Unable to start service matrix-postgres: Failed to start matrix-postgres.service: Unit docker.service failed to load: No such file or directory.`

the docker service in DSM is named `pkg-ContainerManager-dockerd.service.`

I can manually start and stop the service using this command: `sudo systemctl start pkg-ContainerManager-dockerd.service`

I have tried finding where I can change it for myself but no luck.

Appreciate all of your help.

**Comment by Twolitrepinto** [comment]
> I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.
> 
> After that, I specified the DSM Docker location in my vars file as follows: `devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`
> 
> It would be appreciated if this change can be approved.

@cksit Sorry to be a pain, but I cannot work this out.

DSM 7.2 has Container Manager which is essentially rebranded docker with a GUI, but the docker binaries are in a different location (`/volume1/@appstore/ContainerManager/usr/bin`).
There is no docker.service. listed either, it is `pkg-ContainerManager-dockerd.service`
Can I ask please, how did you get around this?
Did you somehow force the playbook to use this? or use some kind of symlink / alias on the synology side to make docker.service point to the synology one?
I'm at a loss now but I am happy to send you some beer tokens if you can help me solve this.

Thanks again.

**Comment by cksit** [comment]
> > I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.
> 
> > 
> 
> > After that, I specified the DSM Docker location in my vars file as follows: `devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`
> 
> > 
> 
> > It would be appreciated if this change can be approved.
> 
> 
> 
> @cksit Sorry to be a pain, but I cannot work this out.
> 
> 
> 
> DSM 7.2 has Container Manager which is essentially rebranded docker with a GUI, but the docker binaries are in a different location (`/volume1/@appstore/ContainerManager/usr/bin`).
> 
> There is no docker.service listed either, it is `pkg-ContainerManager-dockerd.service`
> 
> Can I ask please, how did you get around this?
> 
> Did you somehow force the playbook to use this? or use some kind of symlink / alias on the synology side to make docker.service point to the synology one?
> 
> I'm at a loss now but I am happy to send you some beer tokens if you can help me solve this.
> 
> 
> 
> Thanks again.
> 
> 

I am happy to help. However, you are in the very early stages of installing this project in DSM. I am tidying up my notes on how to do this. Once I finish, you should be able to follow the steps and instructions to do it yourself.

I will let you know once I finished, should be tonight (my time🙂).

**Comment by cksit** [comment]
@Twolitrepinto please check my newly created repository below
https://github.com/cksit/dsm-pre-for-matrix-ansible-deploy

To avoid hijacking this thread, if you have further question, feel free to discuss on the above repo.

**Comment by spantaleev** [comment]
All of our services used to depend on `docker.service`  (it was hardcoded), but this dependency has been made configurable via a new `devture_systemd_docker_base_docker_service_name` variable (see https://github.com/devture/com.devture.ansible.role.systemd_docker_base/commit/0241c71a4c08ff5e203b55d50a424387e3b077c8).

You can either add `devture_systemd_docker_base_docker_service_name: ''` to your `vars.yml` file to completely eliminate adding a dependency on Docker, or you can point it to your own Docker service (e.g. `devture_systemd_docker_base_docker_service_name: pkg-ContainerManager-dockerd.service`).

**Comment by Twolitrepinto** [comment]
> All of our services used to depend on `docker.service` (it was hardcoded), but this dependency has been made configurable via a new `devture_systemd_docker_base_docker_service_name` variable (see [devture/com.devture.ansible.role.systemd_docker_base@0241c71](https://github.com/devture/com.devture.ansible.role.systemd_docker_base/commit/0241c71a4c08ff5e203b55d50a424387e3b077c8)).
> 
> You can either add `devture_systemd_docker_base_docker_service_name: ''` to your `vars.yml` file to completely eliminate adding a dependency on Docker, or you can point it to your own Docker service (e.g. `devture_systemd_docker_base_docker_service_name: pkg-ContainerManager-dockerd.service`).

This is nice to know.

I have managed to get it working now using a link to docker.service as recommended but @cksit.
This works fine but requires a scheduled task on boot and shutdown to add and remove this link within DSM.
Adding this variable should negate the need to do that.

Thank you again for your help.

**Pull request merged**
