### PR TITLE
Initial mx-puppet-slack bridge role

### PR DESCRIPTION
**Pull request by rbelem**

### CODE REVIEW

**Comment by spantaleev** [comment]
Is this ready for reviewing/merging or there's something else you'd like to do first? :)

**Comment by rbelem** [comment]
Only docs are missing :-) I will write it today and add another PR for mx-puppet-discord.

**Comment by Cadair** [comment]
:rocket:

**Comment by spantaleev** [comment]
I haven't tested this, but it looks good! Thank you! :+1:

**Pull request merged**
