### PR TITLE
update element v1.11.11 -> v1.11.12

### PR DESCRIPTION
**Pull request by joecool1029**
fixes jitsi issue

### CODE REVIEW

**Comment by aaronraimist** [comment]
Tag does not exist yet https://github.com/vector-im/element-web/actions/runs/3330535906

**Comment by aaronraimist** [comment]
Exists now 👍

**Comment by joecool1029** [comment]
Whoops, I'll be sure to check the available tags next time!

**Comment by aaronraimist** [comment]
@joecool1029 No problem. Normally they are ready quickly after the release is made but they have been having some issues lately.

**Pull request merged**
